version: "3"

services:
  backend:
    build: ./app
    ports:
      - "3000:3000"
    container_name: backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    container_name: frontend
    depends_on:
      - backend
    restart: always
